services:
  jizhang:
    container_name: jizhang
    hostname: jizhang
    image: ghcr.io/freakinaaa/jizhang2:latest
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data
      - PORT=3133
      - HOST=0.0.0.0
    ports:
      - "3133:3133"
    volumes:
      - "./data:/data"
    restart: unless-stopped
